/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> Build Infos
* Version           -> 1.0.0.1231
* Author            -> Jan Homann @ Workstadion.: XXXJANIIIX3XXX
* Build Date        -> 31.12.2017 11:19:49
* Description       -> Building infos from Preprocessor
*
*
*
*/

#ifndef _BUILD_INFO_H_
#define _BUILD_INFO_H_

/* buildVer
* @para             -> none
* @return           -> pointer @ string address
* @description      -> build info of project
*/
char *buildVer(void);

#endif // _BUILD_INFO_H_
